- name: Provision Production EC2
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    instance_name: devops-prod
    key_name: flask_running_app_staging_key
    instance_type: t2.micro
    security_group: flask_running_app_staging_sg
    image_id: ami-0866a3c8686eaeeba
    region: us-east-1

  tasks:
    - name: Launch EC2 instance
      ec2_instance:
        name: "{{ instance_name }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ security_group }}"
        image_id: "{{ image_id }}"
        region: "{{ region }}"
        wait: yes
      register: ec2_output

    - name: Get instance info using instance ID
      ec2_instance_info:
        region: "{{ region }}"
        instance_ids:
          - "{{ ec2_output.instance_ids[0] }}"
      register: prod_info

    - name: Add production instance to inventory
      add_host:
        hostname: "{{ prod_info.instances[0].public_ip_address }}"
        groupname: prod
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    - name: Wait for SSH
      wait_for:
        host: "{{ prod_info.instances[0].public_ip_address }}"
        port: 22
        delay: 20
        timeout: 300
        state: started

- name: Install Docker and Deploy App
  hosts: prod
  remote_user: ubuntu
  become: yes

  vars:
    image_name: ysafdar/devops-app
    image_tag: "{{ app_tag }}"

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Remove existing container
      shell: docker rm -f devops-app || true

    - name: Pull Docker image
      shell: docker pull "{{ image_name }}:{{ image_tag }}"

    - name: Run Docker container on port 80
      shell: docker run -d --name devops-app -p 80:8000 "{{ image_name }}:{{ image_tag }}"
