- name: Provision Production EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    instance_name: devops-prod
    key_name: flask_running_app_staging_key
    instance_type: t2.micro
    security_group: flask_running_app_staging_sg
    image_id: ami-0866a3c8686eaeeba
    region: us-east-1

  tasks:
    - name: Launch EC2 instance
      ec2_instance:
        name: "{{ instance_name }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ security_group }}"
        image_id: "{{ image_id }}"
        region: "{{ region }}"
        wait: yes
      register: ec2_output

    - name: Add new instance to inventory
      add_host:
        hostname: "{{ ec2_output.instances[0].public_ip_address }}"
        groupname: prod

    - name: Wait for SSH
      wait_for:
        host: "{{ ec2_output.instances[0].public_ip_address }}"
        port: 22
        delay: 20
        timeout: 300
